# This workflow will run all checks required for a PR to be merged.

name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # be sure to also update these in other workflows
  DENO_DIR: deno_dir
  DENO_VERSION: "2.4.1"

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.3
        with:
          deno-version: v2.4.1

      - name: fmt
        run: deno fmt --check

      - name: Install Dependencies
        run: deno task install-deps

      - name: Check Types
        run: deno task check

      - name: Build
        run: deno task build-gameserver --target linux
