name: release

permissions:
  contents: write # For creating releases.

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Name of tag and GitHub release title'
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.3
        with:
          deno-version: v2.4.1

      - name: Install Dependencies
        run: deno task install-deps

      - name: Build gameserver
        run: deno task build-gameserver --archive

      - name: Build servermanager
        run: deno task build-servermanager --archive

      - name: Build adminpanel
        run: deno task build-adminpanel

      - name: Build client
        run: deno task build-client ${{ inputs.version }}

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ inputs.version }}
          draft: true
          files: |
            gameServer/out/*
            serverManager/out/*
            adminPanel/out/adminPanel.tar
            client/out/client.tar
